project:
  type: website

website:
  title: "Menu"
  description: "Personal Website"
  image: T.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: art.qmd
        text: Art in R
      - href: Rexamples.qmd
        text: R
  favicon: T.png

format:
  html:
    theme: 
      light: flatly
    backgroundcolor: "#ecf0f1" 
    css: styles.css
    toc: true



