project:
  type: website

website:
  title: "Menu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - art.qmd
  favicon: T.png

format:
  html:
    theme: 
      light: flatly
    backgroundcolor: "#ecf0f1" 
    css: styles.css
    toc: true



