---
title: "Art"
code-fold: true
---

# Art using R

```{r}
#| echo: false
#| message: false
#| warning: false
#| include: false
library(tidyverse)
library(scico)
library(ambient)
library(particles)
#library(ggforce)
#library(ggraph)
library(tidygraph)
library(RColorBrewer)
library(deldir)
knitr::opts_chunk$set(warning = FALSE, results = "hide")
```

```{r}
#| include: false
theme_void2 <- \() {
  theme_void() %+replace% theme(
    plot.background = element_rect(fill = "#ecf0f1", color = NA),
    legend.background = element_rect(fill = "#ecf0f1", color = NA),
    panel.background = element_rect(fill = "#ecf0f1", color = NA),
    strip.background = element_rect(fill = "#ecf0f1", color = NA)
  )
}
theme_set(theme_void2())
background <- "#ecf0f1"
```


```{r}
#| echo: false
#| eval: false
#| code-fold: false
circles <- data.frame(
  x0 = rep(1:3, 3),
  y0 = rep(1:3, each = 3),
  r = seq(0.1, 1, length.out = 9)
)

# Behold some circles
ggplot() +
  geom_circle(aes(x0 = x0, y0 = y0, r = r, fill = r), data = circles, show.legend = F)
```

## Shapes

```{r}
make_df <- \(n = 6) {
  expand.grid(x = seq(0, 1, length.out = n),
         y = seq(0, 1, length.out = n)) |>
    tibble(
      color = sample(1:6, n^2, replace = TRUE),
      stroke = sample(5:9, n^2, replace = TRUE),
      shape = sample(c(7:10, 12:13), n^2, replace = TRUE)
    )
}

draw <- \(seed = 1) {
  set.seed(seed)
  make_df() |>
    ggplot(aes(
      x = x,
      y = y,
      color = factor(color)
    )) +
    geom_point(aes(
      size = 1,
      stroke = stroke,
      shape = factor(shape)
    ), show.legend = F) +
    coord_cartesian(xlim = c(-.25, 1.25), ylim = c(-.25, 1.25)) +
    scale_color_brewer(palette = "Set1")
}

#map(1:5, draw)
draw(5)
```

```{r}
#| fig-asp: 1
tribble(
  ~x,  ~y,  ~color,  ~size,  ~shape,  ~stroke,
  -1,   1,  "left",    20,        8,       10, 
  1,    1, "right",    25,       10,       10,
  0, -1.5, "mouth",    25,        9,       10,
  0,    0,  "nose",    15,        2,       10     
) |>
  ggplot() +
  geom_point(aes(
    x = x,
    y = y,
    color = color,
    size = size,
    shape = shape,
    stroke = stroke
  ),
  show.legend = FALSE) +
  scale_size_identity() +
  scale_shape_identity() +
  scale_color_brewer(palette = "Pastel1") + 
  coord_cartesian(xlim = c(-2, 2), ylim = c(-2, 2))
```

## Delaunay

[Delaunay Triangulation](https://en.wikipedia.org/wiki/Delaunay_triangulation)

```{r}
del_df <- \(n = 10){
  expand.grid(x = seq(0, 1, length.out = n),
              y = seq(0, 1, length.out = n)) |>
    tibble( 
      fill = sample(letters[1:3], n^2, replace = TRUE)
    )
}

del_df() |>
  ggplot(aes(x, y)) +
  ggforce::geom_delaunay_segment2(
    aes(color = fill, group = -1),
    size = 2,
    lineend = "round",
    show.legend = FALSE
  )

```

```{r}
del_df2 <- \(n = 50, groups = 3, prob = NULL){
  tibble(
  x = sample(1:n, size = n %/% 2, prob = prob),
  y = sample(1:n, size = n %/% 2, prob = prob),
  fill = sample(letters[1:groups], size = n %/% 2, replace = TRUE)
  )
}

make_del2 <- \(seed = 1) {
  set.seed(seed)
  del_df2() |>
    ggplot(aes(x, y)) +
    ggforce::geom_delaunay_segment2(
      aes(color = fill, group = -1),
      size = 2,
      lineend = "round",
      show.legend = FALSE
    )
}

make_del2(2)
```

## Voronoi

[Voronoi Diagram](https://en.wikipedia.org/wiki/Voronoi_diagram)

```{r}
vor_df <- \(n = 50, groups = 3, prob = NULL) {
  tibble(
    x = sample(1:n, size = n %/% 2, prob = prob),
    y = sample(1:n, size = n %/% 2, prob = prob),
    fill = sample(letters[1:groups], size = n %/% 2, replace = TRUE)
  )
}

make_vor <- \(seed = 1) {
  set.seed(seed)
  vor_df() |>
    ggplot(aes(x, y, group = -1L)) +
    ggforce::geom_voronoi_tile(aes(fill = fill), show.legend = FALSE) +
    ggforce::geom_voronoi_segment(color = background)
}

make_vor(1)
```

## Raster

```{r}
#| echo: false
func <- \(vec) {
  n <- sqrt(length(vec))
  s <- vector(mode = "numeric", length = 0)
  
  mat <- matrix(vec, nrow = n, byrow = TRUE)
  
  for (i in (1:n)) {
    s <- c(s, matricks::antidiag(as.matrix(mat[1:i, 1:i])))
  }
  for (i in (1:(n - 1))) {
    s <- c(s, matricks::antidiag(as.matrix(mat[(i + 1):n, (i + 1):n])))
  }
  s 
  # |> matrix(nrow = n, byrow = FALSE)
  # %*% matricks::antidiag(1, nrow = n, ncol = n)
}
```

```{r}
#| fig-asp: 1
r_df <- \(n = 501){
  expand.grid(x = seq(0, 1, length.out = n),
              y = seq(0, 1, length.out = n)) |>
    tibble( 
      fill1 = 1:n^2,
      fill2 = func(c(1:n^2))
    )
}

r_df() |>
  ggplot(aes(x, y)) +
  geom_raster(aes(fill = factor(fill1)),
              interpolate = TRUE,
              show.legend = FALSE) + 
  scale_fill_viridis_d(option = "turbo") + 
  coord_equal()

r_df() |>
  ggplot(aes(x, y)) +
  geom_raster(aes(fill = factor(fill2)),
              interpolate = TRUE,
              show.legend = FALSE) + 
  scale_fill_viridis_d(option = "turbo") + 
  coord_equal()
```

## Bubbles

```{r}
p_df <- \(n = 25, groups = 5, prob = NULL) {
  tibble(
    x = sample(1:(n * 2), size = n, prob = prob),
    y = sample(1:(n * 2), size = n, prob = prob),
    fill = sample(letters[1:groups], size = n, replace = TRUE),
    size = sample(30:50, size = n, replace = TRUE)
  )
}

bubbles <- \(seed = 1, number_of_bubbles = 25) {
  set.seed(seed)
  p_df(number_of_bubbles) |>
    ggplot(aes(x, y)) +
    geom_point(
      aes(
        fill = fill,
        color = fill,
        size = size
      ),
      stroke = .1,
      shape = 21,
      alpha = .35,
      show.legend = FALSE
    ) +
    scale_size_identity()
}

bubbles(seed = 5)
```
